use env instead of machine id

diff --git a/bin/octoswarm b/bin/octoswarm
--- a/bin/octoswarm
+++ b/bin/octoswarm
@@ -1,16 +1,23 @@
 #!/bin/bash
 
-assert_required_params(){
-  local machine_id="$1"
+assert_required_tools(){
+  if [ "$(which envsubst)" == "" ]; then
+    echo "Missing 'envsubst' utility. 'brew install gettext; brew link gettext' to install."
+    exit 1
+  fi
+}
 
-  if [ -n "$machine_id"  ]; then
+assert_required_params(){
+  local docker_machine_env="$1"
+
+  if [ -n "$docker_machine_env"  ]; then
     return 0
   fi
 
   usage
 
-  if [ -z "$machine_id" ]; then
-    echo "machine_id is missing"
+  if [ -z "$docker_machine_env" ]; then
+    echo "docker_machine_env is missing"
   fi
 
   exit 1
@@ -59,6 +66,26 @@ setup_tab_shell() {
   tmux new-window -t "${session}:1" -n "shell" || return 1
 }
 
+setup_docker_machine() {
+  local session="$1"
+  local docker_machine_env="$2"
+  if [ "$docker_machine_env" != "dev" ]; then
+    export RAW_MACHINE_STORAGE_PATH="$HOME/Projects/Octoblu/swarm-$docker_machine_env/machine-template"
+    export MACHINE_STORAGE_PATH="$HOME/Projects/Octoblu/swarm-$docker_machine_env/machine"
+    tmux set-environment -t $session MACHINE_STORAGE_PATH "$MACHINE_STORAGE_PATH"
+    mkdir -p "$MACHINE_STORAGE_PATH"
+    cp -rfp $RAW_MACHINE_STORAGE_PATH/* $MACHINE_STORAGE_PATH
+    pushd $MACHINE_STORAGE_PATH
+      for file in `find . -iname '*.json'`; do
+        cat "$file" | envsubst > "$file.tmp" && mv "$file.tmp" "$file"
+      done
+      for file in `find . -iname 'id_rsa'`; do
+        chmod 600 "$file"
+      done
+    popd
+  fi
+}
+
 start_server() {
   tmux start-server
 }
@@ -100,7 +127,7 @@ script_directory(){
 }
 
 usage(){
-  echo 'USAGE: octomux <machine_id>'
+  echo 'USAGE: octomux <docker_machine_env>'
   echo ''
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
@@ -119,7 +146,7 @@ version(){
 }
 
 main() {
-  local machine_id="$1";
+  local docker_machine_env="$1";
   while [ "$1" != "" ]; do
     local param="$1"
     local value="$2"
@@ -139,20 +166,24 @@ main() {
           exit 1
         fi
         if [ ! -z "$param" ]; then
-          machine_id="$param"
+          docker_machine_env="$param"
         fi
         ;;
     esac
     shift
   done
 
-  assert_required_params "$machine_id"
+  assert_required_params "$docker_machine_env"
+  assert_required_tools
 
-  local session="octomux-$machine_id"
+  local machine_id="octoblu-$docker_machine_env-manager-1"
+  local session="octoswarm-$docker_machine_env"
+
   start_server
   has_session "$session"
   if [ "$?" != "0" ]; then
     create_session "$session"
+    setup_docker_machine "$session" "$docker_machine_env"
     setup_session "$session" "$machine_id"
     setup_tab_zero "$session"
     setup_tab_shell "$session"
