v5.0.0 require OCTOSWARM_LOGENTRIES_TOKEN, fixed versioning, cleaned up, and improved octoswarm speed

diff --git a/bin/stack b/bin/stack
--- a/bin/stack
+++ b/bin/stack
@@ -1,26 +1,6 @@
 #!/bin/bash
 
-debug() {
-  local debug_key='stack'
-  local cyan='\033[0;36m'
-  local no_color='\033[0;0m'
-  if [ -z "$DEBUG" ]; then
-    return 0
-  fi
-  echo "$debug_key" | grep "$DEBUG"
-  local is_valid_debug="$?"
-  if [ "$debug_key" == '*' -a "$is_valid_debug" != "0" ]; then
-    return 0
-  fi
-  local message="$@"
-  (>&2 echo -e "[${cyan}${debug_key}${no_color}]: $message")
-}
-
-fatal() {
-  local message="$1"
-  (>&2 echo "Error: $message")
-  exit 1
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 script_directory(){
   local source="${BASH_SOURCE[0]}"
@@ -37,6 +17,10 @@ script_directory(){
   echo "$dir"
 }
 
+debug() {
+  debug_core "stack" "$@"
+}
+
 usage(){
   echo 'USAGE: stack <script-name> [options]'
   echo ''
@@ -46,16 +30,6 @@ usage(){
   echo 'Environment:'
   echo '  DEBUG              print debug output'
   echo '  OVERRIDE_SAY_YES_OVERRIDE  override "y" on any confirmation prompt'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 run_script() {
diff --git a/bin/swarm-generate-machine-id b/bin/swarm-generate-machine-id
--- a/bin/swarm-generate-machine-id
+++ b/bin/swarm-generate-machine-id
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+
 assert_required_params(){
   local role_name="$1"
 
@@ -28,12 +30,6 @@ assert_required_env() {
   exit 1
 }
 
-fatal() {
-  local message="$1"
-  echo "Error: $message"
-  exit 1
-}
-
 script_directory(){
   local source="${BASH_SOURCE[0]}"
   local dir=""
@@ -55,16 +51,6 @@ usage(){
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
   echo '  -v, --version      print the version'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 main() {
diff --git a/bin/swarm-get-latest-docker-url b/bin/swarm-get-latest-docker-url
--- a/bin/swarm-get-latest-docker-url
+++ b/bin/swarm-get-latest-docker-url
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+
+debug() {
+  debug_core "swarm-get-latest-docker-url" "$@"
+}
+
 assert_required_params(){
   local service_name="$1"
 
@@ -29,12 +35,6 @@ assert_required_env() {
   exit 1
 }
 
-fatal() {
-  local message="$1"
-  echo "Error: $message"
-  exit 1
-}
-
 script_directory(){
   local source="${BASH_SOURCE[0]}"
   local dir=""
@@ -58,16 +58,6 @@ usage(){
   echo '  -v, --version      print the version'
   echo 'Environment:'
   echo '  BEEKEEPER_URI      the beekeeper uri, with auth'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 get_beekeeper_docker_url() {
diff --git a/bin/swarm-join-manager b/bin/swarm-join-manager
--- a/bin/swarm-join-manager
+++ b/bin/swarm-join-manager
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+
 assert_required_params(){
   local machine_id="$1"
   local ip_address="$2"
@@ -22,19 +24,7 @@ assert_required_params(){
 }
 
 debug() {
-  local debug_key='swarm-join-manager'
-  local cyan='\033[0;36m'
-  local no_color='\033[0;0m'
-  if [ -z "$DEBUG" ]; then
-    return 0
-  fi
-  echo "$debug_key" | grep "$DEBUG"
-  local is_valid_debug="$?"
-  if [ "$debug_key" == '*' -a "$is_valid_debug" != "0" ]; then
-    return 0
-  fi
-  local message="$@"
-  (>&2 echo -e "[${cyan}${debug_key}${no_color}]: $message")
+  debug_core "swarm-join-manager" "$@"
 }
 
 fatal() {
@@ -68,16 +58,6 @@ usage(){
   echo '  -v, --version      print the version'
   echo 'Environment:'
   echo '  DEBUG              print debug output'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 join_manager() {
diff --git a/stack/stack-add-service b/stack/stack-add-service
--- a/stack/stack-add-service
+++ b/stack/stack-add-service
@@ -15,7 +15,7 @@ script_directory(){
   echo "$dir"
 }
 
-source "$(script_directory)/utils" || fatal 'unable to load utils'
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 debug() {
   debug_core "stack-add-service" "$@"
@@ -46,16 +46,6 @@ usage(){
   echo '  -v, --version      print the version'
   echo 'Environment:'
   echo '  DEBUG              print debug output'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 main() {
diff --git a/stack/stack-auto-configure-dns b/stack/stack-auto-configure-dns
--- a/stack/stack-auto-configure-dns
+++ b/stack/stack-auto-configure-dns
@@ -37,7 +37,7 @@ script_directory(){
   echo "$dir"
 }
 
-source "$(script_directory)/utils" || fatal 'unable to load utils'
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params() {
   local domain="$1"
@@ -77,17 +77,6 @@ usage(){
   echo '  DEBUG            print debug output'
   echo ''
 }
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown-version"
-  fi
-}
-
 # Script Functions
 
 find_services(){
diff --git a/stack/stack-create-elb b/stack/stack-create-elb
--- a/stack/stack-create-elb
+++ b/stack/stack-create-elb
@@ -15,7 +15,7 @@ script_directory(){
   echo "$dir"
 }
 
-source "$(script_directory)/utils" || fatal 'unable to load utils'
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 debug() {
   debug_core "stack-create-elb" "$@"
@@ -52,16 +52,6 @@ usage(){
   echo '  AWS_SECRET_ACCESS_KEY  AWS Secret Key'
   echo '  AWS_DEFAULT_REGION     AWS Default Region'
   echo '  DEBUG                  print debug output'
-}
-
-version(){
-  local directory="$(script_directory)/.."
-
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
-  else
-    echo "unknown"
-  fi
 }
 
 main() {
diff --git a/stack/stack-ensure-service b/stack/stack-ensure-service
--- a/stack/stack-ensure-service
+++ b/stack/stack-ensure-service
@@ -17,7 +17,7 @@ script_directory(){
   echo "$dir"
 }
 
-source "$(script_directory)/utils" || fatal 'unable to load utils'
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 debug() {
   debug_core "stack-ensure-service" "$@"
@@ -35,10 +35,10 @@ usage(){
 }
 
 version(){
-  local directory="$(script_directory)/.."
 
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
+
+  if [ -f "$VERSION_FILE_PATH" ]; then
+    cat "$VERSION_FILE_PATH"
   else
     echo "unknown"
   fi
@@ -316,8 +316,8 @@ ensure_service() {
     fi
     opt_traefik="$labelFlag traefik.frontend.rule=${frontendRule} $labelFlag traefik.port=80 $labelFlag traefik.docker.network=traefik"
   fi
-  if [ "$logentries" == "true" -a -n "$LOGENTRIES_TOKEN" ]; then
-    opt_logentries="--log-driver logentries --log-driver logentries-token=$LOGENTRIES_TOKEN"
+  if [ "$logentries" == "true" -a -n "$OCTOSWARM_LOGENTRIES_TOKEN" ]; then
+    opt_logentries="--log-driver logentries --log-driver logentries-token=$OCTOSWARM_LOGENTRIES_TOKEN"
   fi
 
   for port in $publish; do
diff --git a/stack/stack-update-changed-env b/stack/stack-update-changed-env
--- a/stack/stack-update-changed-env
+++ b/stack/stack-update-changed-env
@@ -15,7 +15,7 @@ script_directory(){
   echo "$dir"
 }
 
-source "$(script_directory)/utils" || fatal 'unable to load utils'
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 debug() {
   debug_core "stack-update-changed-env" "$@"
@@ -92,10 +92,10 @@ usage(){
 }
 
 version(){
-  local directory="$(script_directory)/.."
+  
 
-  if [ -f "$directory/VERSION" ]; then
-    cat "$directory/VERSION"
+  if [ -f "$VERSION_FILE_PATH" ]; then
+    cat "$VERSION_FILE_PATH"
   else
     echo "unknown"
   fi
