handle both eth0 and ens3

diff --git a/bin/swarm-initialize b/bin/swarm-initialize
--- a/bin/swarm-initialize
+++ b/bin/swarm-initialize
@@ -39,6 +39,26 @@ version(){
   fi
 }
 
+get_interface() {
+  local machine_id="$1"
+  local ifconf="$(docker-machine ssh "$machine_id" ifconfig)"
+  if [ "$?" != "0" ]; then
+    fatal 'Unable to ssh into machine'
+    return 1
+  fi
+  echo "$ifconf" | grep eth0 &> /dev/null
+  if [ "$?" == "0" ]; then
+    echo 'eth0'
+    return 0
+  fi
+  echo "$ifconf" | grep ens3 &> /dev/null
+  if [ "$?" == "0" ]; then
+    echo 'ens3'
+    return 0
+  fi
+  return 1
+}
+
 main() {
   local machine_id="$1";
   while [ "$1" != "" ]; do
@@ -67,7 +87,11 @@ main() {
     shift
   done
 
-  docker $(docker-machine config "$machine_id") swarm init  --advertise-addr ens3 --listen-addr ens3
+  local interface="$(get_interface "$machine_id")"
+  if [ "$?" != "0" ]; then
+    fatal "$interface"
+  fi
+  docker $(docker-machine config "$machine_id") swarm init  --advertise-addr "$interface" --listen-addr "$interface"
 }
 
 main "$@"
