v1.0.1 fixed swarm-follow-instance and swarm-exec-instance

diff --git a/bin/swarm-exec-instance b/bin/swarm-exec-instance
--- a/bin/swarm-exec-instance
+++ b/bin/swarm-exec-instance
@@ -10,6 +10,15 @@ assert_machine_name(){
     exit 1
   fi
 }
+
+assert_docker_container_name() {
+  local docker_container_name="$1"
+  if [ -z "$docker_container_name" ]; then
+    return 1
+  fi
+  return 0
+}
+
 assert_required_params(){
   local service_name="$1"
   local instance_name="$2"
@@ -130,19 +139,37 @@ get_docker_instance_name_suffix() {
   | awk '{print $1}'
 }
 
-follow_instance() {
+exec_instance() {
   local service_name="$1"
   local instance_name="$2"
   local cmd=$3
 
   local machine_name="$(get_docker_machine_name $service_name $instance_name)"
-  assert_machine_name "$machine_name" "$service_name" "$instance_name"
+  assert_machine_name "$machine_name" "$service_name" "$instance_name" || return 1
+
   local docker_instance_name="$(get_docker_instance_name $service_name $instance_name)"
   local docker_container_name="$(get_docker_container_name "$machine_name" "$docker_instance_name")"
+
+  assert_docker_container_name "$docker_container_name" || return 1
+
   local docker_config="$(docker-machine config $machine_name 2> /dev/null)"
 
   echo "Executing $cmd on $docker_container_name..."
   docker $docker_config exec -it "$docker_container_name" $cmd
+}
+
+try_exec_instance() {
+  local service_name="$1"
+  local instance_name="$2"
+  local cmd="$3"
+  local attempt=0
+	while [ $attempt -lt 10 ]; do
+		exec_instance "$service_name" "$instance_name" "$cmd" && return 0
+		echo "$attempt/10 of exec instance, retrying"
+		let "attempt+=1"
+	done
+	echo 'failed to exec instance'
+	exit 1
 }
 
 main() {
@@ -181,7 +208,7 @@ main() {
   done
 
   assert_required_params "$service_name" "$instance_name" "$cmd"
-  follow_instance "$service_name" "$instance_name" "$cmd"
+  exec_instance "$service_name" "$instance_name" "$cmd"
 }
 
 main "$@"
diff --git a/bin/swarm-follow-instance b/bin/swarm-follow-instance
--- a/bin/swarm-follow-instance
+++ b/bin/swarm-follow-instance
@@ -10,6 +10,15 @@ assert_machine_name(){
     exit 1
   fi
 }
+
+assert_docker_container_name() {
+  local docker_container_name="$1"
+  if [ -z "$docker_container_name" ]; then
+    return 1
+  fi
+  return 0
+}
+
 assert_required_params(){
   local service_name="$1"
   local instance_name="$2"
@@ -133,15 +142,31 @@ follow_instance() {
   local additional_args="$3"
 
   local machine_name="$(get_docker_machine_name "$service_name" "$instance_name")"
-  assert_machine_name "$machine_name" "$service_name" "$instance_name"
+  assert_machine_name "$machine_name" "$service_name" "$instance_name" || return 1
 
   local docker_instance_name="$(get_docker_instance_name "$service_name" "$instance_name")"
   local docker_container_name="$(get_docker_container_name "$machine_name" "$docker_instance_name")"
+
+  assert_docker_container_name "$docker_container_name" || return 1
 
   echo "Following: $service_name.$instance_name ($docker_container_name)"
   local docker_config="$(docker-machine config "$machine_name" 2> /dev/null)"
   docker $docker_config logs --follow $additional_args "$docker_container_name" \
   || echo "Error following: $service_name.$instance_name"
+}
+
+try_follow_instance() {
+  local service_name="$1"
+  local instance_name="$2"
+  local additional_args="$3"
+  local attempt=0
+	while [ $attempt -lt 10 ]; do
+		follow_instance "$service_name" "$instance_name" "$additional_args" && return 0
+		echo "$attempt/10 of following instance, retrying"
+		let "attempt+=1"
+	done
+	echo 'failed to follow instance'
+	exit 1
 }
 
 main() {
@@ -182,7 +207,7 @@ main() {
   done
 
   assert_required_params "$service_name" "$instance_name"
-  follow_instance "$service_name" "$instance_name" "$additional_args"
+  try_follow_instance "$service_name" "$instance_name" "$additional_args"
 }
 
 main "$@"
