more utils

diff --git a/bin/swarm-generate-machine-id b/bin/swarm-generate-machine-id
--- a/bin/swarm-generate-machine-id
+++ b/bin/swarm-generate-machine-id
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+assert_required_params(){
+  local role_name="$1"
+
+  if [ -n "$role_name" ]; then
+    return 0
+  fi
+
+  usage
+
+  if [ -z "$role_name" ]; then
+    echo "role_name is missing"
+  fi
+
+  exit 1
+}
+
 fatal() {
   local message="$1"
   echo "Error: $message"
@@ -22,7 +38,7 @@ script_directory(){
 }
 
 usage(){
-  echo 'USAGE: swarm-start-service <service-name>'
+  echo 'USAGE: swarm-generate-machine-id <role_name>'
   echo ''
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
@@ -39,16 +55,18 @@ version(){
   fi
 }
 
-start_service() {
+stop_service() {
   local service_name="$1"
   local directory="$2"
   pushd "$directory/services/$service_name" > /dev/null
-  ./start
+  echo "stopping $service_name"
+  ./stop
   popd > /dev/null
 }
 
 main() {
-  local service_name="$1";
+  local role_name
+
   while [ "$1" != "" ]; do
     local param="$1"
     local value="$2"
@@ -67,15 +85,19 @@ main() {
           usage
           exit 1
         fi
-        if [ -n "$param" ]; then
-          service_name="$param"
+        if [ -z "$role_name" -a -n "$param" ]; then
+         role_name="${param}"
         fi
         ;;
     esac
     shift
   done
+  assert_required_params "$role_name"
 
-  start_service "$service_name" "$SWARM_ENV_DIR"
+  local NEW_UUID=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-z0-9' | fold -w 6 | head -n 1)
+  local machine_id="$STACK_NAME-$role_name-$NEW_UUID"
+
+  echo "$machine_id"
 }
 
 main "$@"
