updated octoswarm and swarm-get-latest-docker-url and added configure-hub-on-all-services

diff --git a/bin/swarm-get-latest-docker-url b/bin/swarm-get-latest-docker-url
--- a/bin/swarm-get-latest-docker-url
+++ b/bin/swarm-get-latest-docker-url
@@ -16,6 +16,19 @@ assert_required_params(){
   exit 1
 }
 
+assert_required_env() {
+  local beekeeper_uri="$BEEKEEPER_URI"
+  if [ -n "$BEEKEEPER_URI" ]; then
+    return 0
+  fi
+
+  usage
+  if [ -z "$BEEKEEPER_URI" ]; then
+    echo 'Missing BEEKEEPER_URI'
+  fi
+  exit 1
+}
+
 fatal() {
   local message="$1"
   echo "Error: $message"
@@ -43,6 +56,8 @@ usage(){
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
   echo '  -v, --version      print the version'
+  echo 'Environment:'
+  echo '  BEEKEEPER_URI      the beekeeper uri, with auth'
 }
 
 version(){
@@ -57,7 +72,7 @@ version(){
 
 get_beekeeper_docker_url() {
   local service_name="$1"
-  local latest_docker_url="$(curl -s "https://beekeeper.octoblu.com/deployments/$service_name/latest" | jq -r '.docker_url')"
+  local latest_docker_url="$(curl -s "$BEEKEEPER_URI/deployments/$service_name/latest" | jq -r '.docker_url')"
   echo "$latest_docker_url"
 }
 
@@ -90,6 +105,7 @@ main() {
     shift
   done
   assert_required_params "$service_name"
+  assert_required_env
 
   local docker_url="$(get_beekeeper_docker_url "$service_name")"
   if [ -z "$docker_url" -o "$docker_url" == "null" ]; then
