fix swarm-follow-instance

diff --git a/bin/swarm-follow-instance b/bin/swarm-follow-instance
--- a/bin/swarm-follow-instance
+++ b/bin/swarm-follow-instance
@@ -92,6 +92,16 @@ get_docker_machine_name() {
   | awk '{print $4}'
 }
 
+get_docker_container_name() {
+  local machine_name="$1"
+  local instance_name="$2"
+  local docker_config="$(docker-machine config "$machine_name")"
+
+  docker $docker_config ps \
+  | grep "$instance_name" \
+  | awk '{print $1}'
+}
+
 get_docker_instance_name() {
   local service_name="$1"
   local instance_name="$2"
@@ -122,16 +132,16 @@ follow_instance() {
   local instance_name="$2"
   local additional_args="$3"
 
-  local machine_name="$(get_docker_machine_name $service_name $instance_name)"
+  local machine_name="$(get_docker_machine_name "$service_name" "$instance_name")"
   assert_machine_name "$machine_name" "$service_name" "$instance_name"
 
-  local docker_instance_name="$(get_docker_instance_name $service_name $instance_name)"
-  local docker_config="$(docker-machine config $machine_name)"
+  local docker_instance_name="$(get_docker_instance_name "$service_name" "$instance_name")"
+  local docker_container_name="$(get_docker_container_name "$machine_name" "$docker_instance_name")"
 
-  echo "Following $docker_instance_name..."
-  docker $docker_config logs --follow $additional_args "$docker_instance_name"
-
-  echo "following: $service_name.$instance_name"
+  echo "Following: $service_name.$instance_name ($docker_container_name)"
+  local docker_config="$(docker-machine config "$machine_name")"
+  docker $docker_config logs --follow $additional_args "$docker_container_name" \
+  || echo "Error following: $service_name.$instance_name"
 
 }
 
