fix a lot of things

diff --git a/octoswarm b/octoswarm
--- a/octoswarm
+++ b/octoswarm
@@ -13,13 +13,23 @@ debug() {
     return 0
   fi
   local message="$@"
-  (>&2 echo -e "[${cyan}${debug_key}${no_color}]: $message")
+  errecho "[${cyan}${debug_key}${no_color}]: $message"
 }
 
 fatal() {
-  local message="$1"
-  (>&2 echo "Error: $message")
+  local message="$@"
+  errecho "Error: $message"
   exit 1
+}
+
+warn() {
+  local message="$@"
+  errecho "Warning: $message"
+}
+
+errecho() {
+  local message="$@"
+  (>&2 echo -e "$message")
 }
 
 script_directory(){
@@ -100,29 +110,9 @@ check_config_value() {
   return 0
 }
 
-create_machines_files() {
-  if [ ! -d "$RAW_MACHINE_STORAGE_PATH" ]; then
-    (>&2 echo "Missing $RAW_MACHINE_STORAGE_PATH")
-    return 1
-  fi
-  rm -rf $MACHINE_STORAGE_PATH
-  mkdir -p $MACHINE_STORAGE_PATH
-  cp -rfp $RAW_MACHINE_STORAGE_PATH/* $MACHINE_STORAGE_PATH 2> /dev/null
-  local rpl_key="$(escape_value_for_sed "\$HOME/Projects/Octoblu/swarm-$STACK_ENV_NAME/stacks/$STACK_NAME/machine")"
-  local rpl_value="$(escape_value_for_sed $MACHINE_STORAGE_PATH)"
-  pushd "$MACHINE_STORAGE_PATH" > /dev/null
-    for file in `find . -iname '*.json'`; do
-      cat "$file" | sed -e "s/$rpl_key/$rpl_value/" | envsubst > "$file.tmp" && mv "$file.tmp" "$file"
-    done
-    for file in `find . -iname 'id_rsa'`; do
-      chmod 600 "$file"
-    done
-  popd > /dev/null
-}
-
 connect_to_machine() {
-  if [ ! -d "$RAW_MACHINE_STORAGE_PATH" ]; then
-    (>&2 echo "Missing machine-template directory ($RAW_MACHINE_STORAGE_PATH)")
+  if [ ! -d "$MACHINE_STORAGE_PATH/machines" ]; then
+    warn "Missing docker-machine directory ($MACHINE_STORAGE_PATH)"
     return 1
   fi
   local machine_id
@@ -142,17 +132,14 @@ escape_value_for_sed() {
   echo "$1" | sed -e 's/[\/&]/\\&/g'
 }
 
-get_machine_id_unverified(){
-  local random_dir="$(find "$MACHINE_STORAGE_PATH/machines" -iname "$STACK_ENV_NAME-$STACK_NAME-manager-*" -maxdepth 1 -mindepth 1 -type d -print0 | sort --zero-terminated --random-sort | head -1)"
-  echo $(basename "$random_dir")
+get_machine_ids(){
+  find "$MACHINE_STORAGE_PATH/machines" -iname "$STACK_ENV_NAME-$STACK_NAME-manager-*" -maxdepth 1 -mindepth 1 -type d -print0
 }
 
 get_machine_id() {
-  local n=1
-  local max=5
-  until [ $n -ge $max ]; do
-    local machine_id
-    machine_id="$(get_machine_id_unverified)"
+  local machine_id
+  for machine_dir in $(get_machine_ids); do
+    machine_id="$(basename "$machine_dir")"
     validate_machine_id "$machine_id"
     if [ "$?" == "0" ]; then
       debug 'found manager id on try' "$n"
@@ -200,15 +187,9 @@ run_script() {
 validate_machine_id() {
   local machine_id="$1"
   debug 'validating machine id' "$machine_id"
-  local verified_machine_file="$STACK_TMP_DIR/.verfied-$machine_id"
-  if [ -f "$verified_machine_file" ]; then
-    debug "$machine_id is already verified"
-    return 0
-  fi
-  debug 'verifying manager id' "$machine_id"
+  docker-machine config "$machine_id" 2>&1 | grep -i 'error' && return 1
   docker-machine $(docker-machine config "$machine_id") status "$machine_id" 2>&1 | grep -i 'error' \
     && return 1
-  touch "$verified_machine_file"
   return 0
 }
 
@@ -230,21 +211,14 @@ main() {
   assert_stack
   export STACK_NAME="$(get_config_val '.stackName')"
   export STACK_ENV_NAME="$(get_config_val '.stackEnvName')"
-  export STACK_TMP_DIR="/tmp/$STACK_NAME-$STACK_ENV_NAME"
-  export MACHINE_STORAGE_PATH="$STACK_TMP_DIR/machine"
+  export STACK_TMP_DIR="/tmp/$STACK_ENV_NAME-$STACK_NAME"
   mkdir -p "$MACHINE_STORAGE_PATH"
 
-  create_machines_files
   connect_to_machine
 
   shift
   debug "running script $script_name"
   run_script "$script_name" "$@"
-  eval $(docker-machine env --shell=bash --unset)
-  unset STACK_NAME
-  unset STACK_TMP_DIR
-  unset STACK_ENV_NAME
-  unset MACHINE_STORAGE_PATH
   exit $?
 }
 
diff --git a/stack/stack-ensure-cluster b/stack/stack-ensure-cluster
--- a/stack/stack-ensure-cluster
+++ b/stack/stack-ensure-cluster
@@ -22,7 +22,7 @@ debug() {
 }
 
 usage(){
-  echo 'USAGE: stack-ensure-cluster [/path/to/cluster.json]'
+  echo 'USAGE: stack-ensure-cluster'
   echo 'Description: bootstrap, or update, a cluster'
   echo ''
   echo 'Arguments:'
@@ -40,26 +40,6 @@ version(){
   else
     echo "unknown"
   fi
-}
-
-assert_required_params(){
-  local config_path="$1"
-
-  if [ -n "$config_path" -a -f "$config_path"  ]; then
-    return 0
-  fi
-
-  usage
-
-  if [ -z "$config_path" ]; then
-    echo "config_path is missing"
-  fi
-
-  if [ ! -f "$config_path" ]; then
-    echo "$config_path is not a file"
-  fi
-
-  exit 1
 }
 
 require_config_value() {
@@ -109,7 +89,7 @@ get_config_array() {
 }
 
 is_stack_empty() {
-  if [ -d "$RAW_MACHINE_STORAGE_PATH" ]; then
+  if [ -d "$MACHINE_STORAGE_PATH/machines" ]; then
     return 0
   fi
   return 1
@@ -123,31 +103,8 @@ get_manager_elbs() {
   fi
 }
 
-create_stack(){
-  debug 'about to create stack'
-  local stack_env_name="$(get_config_val '.stackEnvName')"
-  local stack_name="$(get_config_val '.stackName')"
-  local ec2_instance_type="$(get_config_val '.managers.instanceType')"
-  local elbs=( $(get_manager_elbs) )
-  local skip_elb_flag
-
-  if [ ${#elbs[@]} -eq 0 ]; then
-    skip_elb_flag='--skip-elb'
-  fi
-
-  echo "Stack doesn't exist, we are going to create the first manager..."
-  say_yes || fatal 'Exiting due to human fear.'
-
-  env OCTOSWARM_INIT_CMD='stack ensure-cluster' \
-    "$(script_directory)/stack-initialize" "$stack_env_name" "$stack_name" \
-    --ec2-instance-type "$ec2_instance_type" $skip_elb_flag || fatal 'Unable to initialize stack'
-  exit 0
-}
-
 ensure_managers_elb() {
   debug 'ensuring managers elb'
-  local stack_env_name="$(get_config_val '.stackEnvName')"
-  local stack_name="$(get_config_val '.stackName')"
   local elbs=( $(get_manager_elbs) )
   for elb in "${elbs[@]}"; do
     local elb_name="$(echo "$elb" | jq --raw-output ".")"
@@ -157,13 +114,13 @@ ensure_managers_elb() {
       debug "elb $elb_name does not exist"
       echo "ELB count insufficient, creating elb ($elb_name)..."
       say_yes || continue
-      "$(script_directory)/stack-create-elb" "$elb_name"
+      stack create-elb "$elb_name"
     else
       debug "elb $elb_name exists"
     fi
     debug "adding to elb $elb_name"
     for manager_id in $(get_manager_ids); do
-      "$(script_directory)/stack-add-to-elb" "$manager_id" "$elb_name" || fatal 'unable to add to elb'
+      stack add-to-elb "$manager_id" "$elb_name" || fatal 'unable to add to elb'
     done
   done
 }
@@ -173,13 +130,6 @@ ensure_managers() {
   local count="$(get_managers_count)"
   local expected_count="$(get_config_val '.managers.count')"
   local ec2_instance_type="$(get_config_val '.managers.instanceType')"
-  local elbs=( $(get_manager_elbs) )
-  local skip_elb_flag
-
-  if [ ${#elbs[@]} -eq 0 ]; then
-    skip_elb_flag='--skip-elb'
-  fi
-
   if [ "$count" -gt "$expected_count" ]; then
     debug "The current count of managers is greater than expected count"
     debug "SKIPPING..."
@@ -198,8 +148,8 @@ ensure_managers() {
     let "real_count = $count + $i"
     echo "Manager count insufficient, creating manager #$real_count..."
     say_yes || continue
-    "$(script_directory)/stack-create-manager" \
-      --ec2-instance-type "$ec2_instance_type" $skip_elb_flag &
+    stack create-manager \
+      --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for managers to boot'
   wait $(jobs -p)
@@ -230,7 +180,7 @@ ensure_workers() {
     let "real_count = $count + $i"
     echo "Worker count insufficient, creating worker #$real_count..."
     say_yes || continue
-    "$(script_directory)/stack-create-worker" \
+    stack create-worker \
       --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for workers to boot'
@@ -326,7 +276,7 @@ ensure_network() {
   fi
 }
 
-get_service_command() {
+run_service_command() {
   local service="$1"
   local opt_beekeeper
   local opt_docker_sock
@@ -355,6 +305,7 @@ get_service_command() {
   local mountFlag='--mount'
   local publishFlag='--publish'
   local constraintFlag='--constraint'
+  local envFlag='--env'
   local isUpdate='false'
   if [ "$(get_service_spec "$name")" != "null" ]; then
     isUpdate='true'
@@ -362,6 +313,7 @@ get_service_command() {
     mountFlag='--mount-add'
     publishFlag='--publish-add'
     constraintFlag='--constraint-add'
+    envFlag='--env-add'
   fi
   if [ "$network" == "null" ]; then
     network="traefik"
@@ -412,6 +364,13 @@ get_service_command() {
     fi
     opt_traefik="$labelFlag traefik.frontend.rule=${frontendRule} $labelFlag traefik.port=80 $labelFlag traefik.docker.network=traefik"
   fi
+  local env_folder="$STACK_ENV_DIR/$name"
+  if [ -d "$env_folder" ]; then
+    for file in $(ls $env_folder); do
+      value="$(cat "$env_folder/$file")"
+      opt_env="$opt_env $envFlag $file=$value "
+    done
+  fi
 
   for port in $publish; do
     opt_publish="$opt_publish $publishFlag $port"
@@ -429,7 +388,7 @@ get_service_command() {
     if [ "$(has_same_docker_image "$name" "$image")" != 'true' ]; then
       opt_image="--image $image"
     fi
-    echo docker service update \
+    docker service update \
       $opt_replicas \
       $opt_docker_sock \
       $opt_role \
@@ -437,11 +396,11 @@ get_service_command() {
       $opt_beekeeper \
       $opt_with_registry_auth \
       $opt_image \
+      $opt_env \
       "$name"
   else
     debug 'creating service'
-    opt_env="$(docker-service-get-env-args "$name")"
-    echo docker service create \
+    docker service create \
       --name "$name" \
       --network "$network" \
       $opt_mode \
@@ -458,25 +417,15 @@ get_service_command() {
   fi
 }
 
-run_service_command() {
-  local cmd="$@"
-  echo "Do you want to run the following command?"
-  echo "  $cmd"
-  say_yes || return 0
-  debug 'service command' `$cmd 2>&1`
-}
-
 ensure_service() {
   local service="$1"
   local name="$(echo "$service" | jq -r '.name')"
   local count="$(echo "$service" | jq -r '.count')"
-  local command="$(get_service_command "$service")"
-  run_service_command $command
+  run_service_command "$service"
   return $?
 }
 
 main() {
-  local config_path
   while [ "$1" != "" ]; do
     local param="$1"
     local value="$2"
@@ -496,38 +445,19 @@ main() {
           usage
           exit 1
         fi
-        if [ -z "$config_path" ]; then
-          config_path="$param"
-        fi
         ;;
     esac
     shift
   done
 
-  if [ ! -d "$config_path" ]; then
-    config_path="$STACK_DIR/cluster.json"
-  fi
-
-  if [ ! -d "$config_path" ]; then
-    config_path="$PWD/cluster.json"
-  fi
-
-  assert_required_params "$config_path"
-
-  unset STACK_CONFIG_PATH
-  export STACK_CONFIG_PATH="$config_path"
-  debug "config file $STACK_CONFIG_PATH"
-
   assert_required_config
 
-  is_stack_empty || create_stack
+  is_stack_empty || fatal 'Not initialized, run `create-cluster`'
 
   ensure_managers || fatal 'unable to ensure managers'
   ensure_managers_elb || fatal 'unable to ensure managers elb'
   ensure_workers || fatal 'unable to ensure workers'
   ensure_services || fatal 'unable to ensure services'
-
-  unset STACK_CONFIG_PATH
 }
 
 main "$@"
