v12.0.0 disable logging on ensure-machine

diff --git a/stack/stack-ensure-cluster b/stack/stack-ensure-cluster
--- a/stack/stack-ensure-cluster
+++ b/stack/stack-ensure-cluster
@@ -35,7 +35,7 @@ ensure_machines() {
     debug "ensure machine $machine_name"
     stack ensure-machine "$machine_name"
   done
-  wait $(jobs -p)
+  wait "$(jobs -p)"
 }
 
 ensure_managers() {
@@ -75,7 +75,7 @@ ensure_managers() {
       --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for managers to boot'
-  wait $(jobs -p)
+  wait "$(jobs -p)"
 }
 
 ensure_workers() {
@@ -117,7 +117,7 @@ ensure_workers() {
       --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for workers to boot'
-  wait $(jobs -p)
+  wait "$(jobs -p)"
 }
 
 get_service_name() {
@@ -127,8 +127,9 @@ get_service_name() {
 
 ensure_services() {
   debug 'ensure services'
-  get_config_array '.services[]' | while read service; do
-    local name="$(get_service_name "$service")"
+  get_config_array '.services[]' | while read -r service; do
+    local name
+    name="$(get_service_name "$service")"
     stack ensure-service "$name" || fatal "unable to ensure service $name"
   done
 }
@@ -136,7 +137,7 @@ ensure_services() {
 main() {
   while [ "$1" != "" ]; do
     local param="$1"
-    local value="$2"
+    # local value="$2"
 
     case "$param" in
       -h | --help)
@@ -160,11 +161,12 @@ main() {
 
   assert_required_config
 
+  # shellcheck disable=SC2016
   is_stack_empty || fatal 'Not initialized, run `create-cluster`'
 
   ensure_managers || fatal 'unable to ensure managers'
   ensure_workers || fatal 'unable to ensure workers'
-  ensure_machines || fatal 'unable to ensure machines'
+  # ensure_machines || fatal 'unable to ensure machines'
   ensure_services || fatal 'unable to ensure services'
   ensure_managers_elb || fatal 'unable to ensure managers elb'
 }
