make require utils and debug consistent, use SCRIPT_NAME for everything

diff --git a/stack/stack-add-to-elb b/stack/stack-add-to-elb
--- a/stack/stack-add-to-elb
+++ b/stack/stack-add-to-elb
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-add-to-elb"
 
-debug() {
-  debug_core "stack-add-to-elb" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params() {
   local machine_id="$1"
@@ -75,7 +73,7 @@ register_instance() {
 }
 
 usage(){
-  echo 'USAGE: stack-add-to-elb <machine-id> <load-balancer-name>'
+  echo "USAGE: $SCRIPT_NAME <machine-id> <load-balancer-name>"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help             print this help text'
diff --git a/stack/stack-create-elb b/stack/stack-create-elb
--- a/stack/stack-create-elb
+++ b/stack/stack-create-elb
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-create-elb"
 
-debug() {
-  debug_core "stack-create-elb" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params() {
   local load_balancer_name="$1"
@@ -25,7 +23,7 @@ assert_required_params() {
 }
 
 usage(){
-  echo 'USAGE: stack-create-elb <load-balancer-name>'
+  echo "USAGE: $SCRIPT_NAME <load-balancer-name>"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help                       print this help text'
diff --git a/stack/stack-create-machine b/stack/stack-create-machine
--- a/stack/stack-create-machine
+++ b/stack/stack-create-machine
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-create-machine"
 
-debug() {
-  debug_core "stack-create-machine" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params(){
   local machine_id="$1"
@@ -54,7 +52,7 @@ docker_login() {
 }
 
 usage(){
-  echo 'USAGE: stack-create-machine'
+  echo "USAGE: $SCRIPT_NAME" 
   echo ''
   echo 'Arguments:'
   echo '  -h, --help               print this help text'
diff --git a/stack/stack-create-manager b/stack/stack-create-manager
--- a/stack/stack-create-manager
+++ b/stack/stack-create-manager
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-create-manager"
 
-debug() {
-  debug_core "stack-create-manager" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params(){
   local ip_address="$1"
@@ -35,7 +33,7 @@ assert_required_env() {
 }
 
 usage(){
-  echo 'USAGE: stack-create-manager'
+  echo "USAGE: $SCRIPT_NAME"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help               print this help text'
diff --git a/stack/stack-create-worker b/stack/stack-create-worker
--- a/stack/stack-create-worker
+++ b/stack/stack-create-worker
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-create-worker"
 
-debug() {
-  debug_core "stack-create-worker" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params(){
   local ip_address="$1"
@@ -23,7 +21,7 @@ assert_required_params(){
 }
 
 usage(){
-  echo 'USAGE: stack-create-worker'
+  echo "USAGE: $SCRIPT_NAME"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help               print this help text'
diff --git a/stack/stack-exec-instance b/stack/stack-exec-instance
--- a/stack/stack-exec-instance
+++ b/stack/stack-exec-instance
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+SCRIPT_NAME="stack-exec-instance"
+
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+
 assert_machine_name(){
   local machine_name="$1"
   local service_name="$2"
@@ -47,13 +51,13 @@ assert_required_params(){
 }
 
 usage(){
-  echo 'USAGE: swarm-exec-instance <service-name> <instance-name> <cmd>'
+  echo "USAGE: $SCRIPT_NAME <service-name> <instance-name> <cmd>"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
   echo '  -v, --version      print the version'
   echo ''
-  echo 'EXAMPLE: swarm-exec-instance slurry-exchange 1 /bin/bash'
+  echo "EXAMPLE: $SCRIPT_NAME slurry-exchange 1 /bin/bash"
 }
 
 get_service_line(){
diff --git a/stack/stack-follow-instance b/stack/stack-follow-instance
--- a/stack/stack-follow-instance
+++ b/stack/stack-follow-instance
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+SCRIPT_NAME="stack-follow-instance"
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+
 assert_machine_name(){
   local machine_name="$1"
   local service_name="$2"
@@ -41,29 +44,8 @@ assert_required_params(){
   exit 1
 }
 
-fatal() {
-  local message="$1"
-  echo "Error: $message"
-  exit 1
-}
-
-script_directory(){
-  local source="${BASH_SOURCE[0]}"
-  local dir=""
-
-  while [ -h "$source" ]; do # resolve $source until the file is no longer a symlink
-    dir="$( cd -P "$( dirname "$source" )" && pwd )"
-    source="$(readlink "$source")"
-    [[ $source != /* ]] && source="$dir/$source" # if $source was a relative symlink, we need to resolve it relative to the path where the symlink file was located
-  done
-
-  dir="$( cd -P "$( dirname "$source" )" && pwd )"
-
-  echo "$dir"
-}
-
 usage(){
-  echo 'USAGE: follow-instance <service-name> <instance-name> [-- [docker-args]]'
+  echo "USAGE: $SCRIPT_NAME <service-name> <instance-name> [-- [docker-args]]"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
@@ -71,7 +53,7 @@ usage(){
   echo ''
   echo 'docker-args are passed through to the "docker logs" command'
   echo ''
-  echo 'EXAMPLE: swarm-follow-instance slurry-exchange 1 -- --since="1h" --timestamps'
+  echo "EXAMPLE: $SCRIPT_NAME slurry-exchange 1 -- --since=\"1h\" --timestamps"
 }
 
 get_service_line(){
diff --git a/stack/stack-remove-machine b/stack/stack-remove-machine
--- a/stack/stack-remove-machine
+++ b/stack/stack-remove-machine
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
+SCRIPT_NAME="stack-remove-machine"
 
-debug() {
-  debug_core "stack-remove-machine" "$@"
-}
+source "/usr/src/app/stack/utils" || fatal 'unable to load utils'
 
 assert_required_params() {
   local machine_id="$1"
@@ -15,7 +13,7 @@ assert_required_params() {
 }
 
 usage(){
-  echo 'USAGE: stack remove-machine <machine-id>'
+  echo "USAGE: $SCRIPT_NAME <machine-id>"
   echo ''
   echo 'Arguments:'
   echo '  -h, --help                       print this help text'
