cleaning up for the swarm-smart way of doing things

diff --git a/stack/stack-add-service b/stack/stack-add-service
--- a/stack/stack-add-service
+++ b/stack/stack-add-service
@@ -1,11 +1,5 @@
 #!/bin/bash
 
-fatal() {
-  local message="$1"
-  echo "Error: $message"
-  exit 1
-}
-
 script_directory(){
   local source="${BASH_SOURCE[0]}"
   local dir=""
@@ -21,12 +15,37 @@ script_directory(){
   echo "$dir"
 }
 
+source "$(script_directory)/utils" || fatal 'unable to load utils'
+
+debug() {
+  debug_core "stack-add-service" "$@"
+}
+
+assert_required_params(){
+  local service_name="$1"
+
+  if [ -n "$service_name" -a ]; then
+    return 0
+  fi
+
+  usage
+
+  if [ -z "$service_name" ]; then
+    echo "service_name is missing"
+  fi
+
+  exit 1
+}
+
+
 usage(){
-  echo 'USAGE: swarm-init-service <service-name>'
+  echo 'USAGE: stack-add-service <service-name>'
   echo ''
   echo 'Arguments:'
   echo '  -h, --help         print this help text'
   echo '  -v, --version      print the version'
+  echo 'Environment:'
+  echo '  DEBUG              print debug output'
 }
 
 version(){
@@ -39,16 +58,9 @@ version(){
   fi
 }
 
-start_service() {
-  local service_name="$1"
-  local directory="$2"
-  pushd "$directory/services/$service_name" > /dev/null
-  ./start
-  popd > /dev/null
-}
-
 main() {
-  local service_name="$1";
+  local service_name
+
   while [ "$1" != "" ]; do
     local param="$1"
     local value="$2"
@@ -67,15 +79,21 @@ main() {
           usage
           exit 1
         fi
-        if [ -n "$param" ]; then
-          service_name="$param"
+        if [ -z "$service_name" -a -n "$param" ]; then
+         service_name="${param}"
         fi
         ;;
     esac
     shift
   done
 
-  start_service "$service_name" "$SWARM_ENV_DIR"
+  if [ ! -d "$SWARM_ENV_DIR/env.d/$service_name" ]; then
+    fatal "This service does not have an environment"
+  fi
+  echo "Copying environment to stack..."
+  mkdir -p "$STACK_ENV_DIR/env.d/$service_name"
+  cp -rfp $SWARM_ENV_DIR/env.d/$service_name/* "$STACK_ENV_DIR/env.d/$service_name" && \
+    echo "done."
 }
 
 main "$@"
