require traefik network and docker.networks, add all nodes to elb, force docker service update

diff --git a/stack/stack-ensure-cluster b/stack/stack-ensure-cluster
--- a/stack/stack-ensure-cluster
+++ b/stack/stack-ensure-cluster
@@ -49,8 +49,8 @@ ensure_managers_elb() {
       debug "elb $elb_name exists"
     fi
     debug "adding to elb $elb_name"
-    for manager_id in $(get_manager_ids); do
-      stack add-to-elb "$manager_id" "$elb_name" || fatal 'unable to add to elb'
+    for node_id in $(get_node_ids); do
+      stack add-to-elb "$node_id" "$elb_name" || fatal 'unable to add to elb'
     done
   done
 }
diff --git a/stack/stack-remove-services b/stack/stack-remove-services
--- a/stack/stack-remove-services
+++ b/stack/stack-remove-services
@@ -27,7 +27,7 @@ remove_services() {
     if [ "$name" == "" ]; then
       fatal "Could not parse service name"
     fi
-    docker service rm "$name" || fatal "unable to remove service $name"
+    docker service rm "$name" || warn "unable to remove service $name"
   done
 }
 
