v8.5.0 use lecli for follow instance

diff --git a/stack/stack-follow-instance b/stack/stack-follow-instance
--- a/stack/stack-follow-instance
+++ b/stack/stack-follow-instance
@@ -79,7 +79,7 @@ get_docker_container_name() {
   local docker_config
   docker_config="$(docker-machine config "$machine_name" 2> /dev/null)"
 
-  docker $docker_config ps \
+  docker $docker_config ps --no-trunc \
   | grep "$instance_name" \
   | awk '{print $1}'
 }
@@ -129,8 +129,9 @@ follow_instance() {
 
   echo "Following: $service_name.$instance_name ($docker_container_name)"
   docker_config="$(docker-machine config "$machine_name" 2> /dev/null)"
-  docker $docker_config logs --follow $additional_args "$docker_container_name" \
-  || echo "Error following: $service_name.$instance_name"
+  lecli query -n swarm_prod --leql 'where(container_id='$docker_container_name')' -r 'last 5 minutes' \
+    || echo "Error following: $service_name.$instance_name"
+  # docker $docker_config logs --follow $additional_args "$docker_container_name" \
 }
 
 try_follow_instance() {
@@ -138,13 +139,13 @@ try_follow_instance() {
   local instance_name="$2"
   local additional_args="$3"
   local attempt=0
-	while [ $attempt -lt 10 ]; do
-		follow_instance "$service_name" "$instance_name" "$additional_args" && return 0
-		echo "$attempt/10 of following instance, retrying"
-		let "attempt+=1"
-	done
-	echo 'failed to follow instance'
-	exit 1
+  while [ $attempt -lt 10 ]; do
+  follow_instance "$service_name" "$instance_name" "$additional_args" && return 0
+  echo "$attempt/10 of following instance, retrying"
+  let "attempt+=1"
+  done
+  echo 'failed to follow instance'
+  exit 1
 }
 
 main() {
