v12.0.1 fixed disable logging changes

diff --git a/stack/stack-ensure-cluster b/stack/stack-ensure-cluster
--- a/stack/stack-ensure-cluster
+++ b/stack/stack-ensure-cluster
@@ -35,7 +35,8 @@ ensure_machines() {
     debug "ensure machine $machine_name"
     stack ensure-machine "$machine_name"
   done
-  wait "$(jobs -p)"
+  # shellcheck disable=SC2046
+  wait $(jobs -p)
 }
 
 ensure_managers() {
@@ -75,7 +76,8 @@ ensure_managers() {
       --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for managers to boot'
-  wait "$(jobs -p)"
+  # shellcheck disable=SC2046
+  wait $(jobs -p)
 }
 
 ensure_workers() {
@@ -117,7 +119,8 @@ ensure_workers() {
       --ec2-instance-type "$ec2_instance_type" &
   done
   debug 'waiting for workers to boot'
-  wait "$(jobs -p)"
+  # shellcheck disable=SC2046
+  wait $(jobs -p)
 }
 
 get_service_name() {
@@ -166,7 +169,7 @@ main() {
 
   ensure_managers || fatal 'unable to ensure managers'
   ensure_workers || fatal 'unable to ensure workers'
-  # ensure_machines || fatal 'unable to ensure machines'
+  ensure_machines || fatal 'unable to ensure machines'
   ensure_services || fatal 'unable to ensure services'
   ensure_managers_elb || fatal 'unable to ensure managers elb'
 }
