v11.1.0 support ec2 tags, allow 1.13.1 to actually be installed by docker-machine

diff --git a/stack/stack-create-worker b/stack/stack-create-worker
--- a/stack/stack-create-worker
+++ b/stack/stack-create-worker
@@ -27,6 +27,9 @@ usage(){
   echo '  -h, --help               print this help text'
   echo '  -t, --ec2-instance-type  ec2 instance type to spin up'
   echo '                           (default: t2.medium)'
+  echo '  --docker-version         docker version to install'
+  echo '                           (default: latest)'
+  echo '  --ec2-tags               ec2 tags (comma delimited)'
   echo '  -v, --version            print the version'
   echo 'Environment:'
   echo '  DEBUG                    print debug output'
@@ -34,6 +37,8 @@ usage(){
 
 main() {
   local ec2_instance_type="t2.medium"
+  local docker_version
+  local ec2_tags
 
   while [ "$1" != "" ]; do
     local param="$1"
@@ -45,6 +50,14 @@ main() {
         ;;
       -t | --ec2-instance-type)
         ec2_instance_type="$value"
+        shift
+        ;;
+      --docker-version)
+        docker_version="$value"
+        shift
+        ;;
+      --ec2-tags)
+        ec2_tags="$value"
         shift
         ;;
       -v | --version)
@@ -70,7 +83,10 @@ main() {
   machine_id="$(swarm-generate-machine-id worker)"
 
   stack create-machine \
-    --ec2-instance-type "$ec2_instance_type" "$machine_id" || fatal 'unable to create machine'
+    --ec2-tags "$ec2_tags" \
+    --ec2-instance-type "$ec2_instance_type" \
+    --docker-version "$docker_version" \
+    "$machine_id" || fatal 'unable to create machine'
 
   swarm-join-worker --ip-address "$ip_address" --machine-id "$machine_id" || fatal 'unable to join-worker'
 }
