v3.1.0 smarter ensure-service and fixed ensure-cluster

diff --git a/stack/stack-ensure-cluster b/stack/stack-ensure-cluster
--- a/stack/stack-ensure-cluster
+++ b/stack/stack-ensure-cluster
@@ -153,7 +153,7 @@ ensure_services() {
   local services=( $(get_config_array '.services[]') )
   for service in "${services[@]}"; do
     local name="$(get_service_name "$service")"
-    stack ensure-service "$service" || fatal "unable to ensure service"
+    stack ensure-service "$name" || fatal "unable to ensure service $name"
   done
 }
 
