v12.2.0 terminate machine in aws ec2

diff --git a/stack/stack-remove-machine b/stack/stack-remove-machine
--- a/stack/stack-remove-machine
+++ b/stack/stack-remove-machine
@@ -57,18 +57,30 @@ remove_config() {
 double_check() {
   local machine_id="$1"
   local good_to_go=''
-  read -s -p "press 'y' to permanently delete this machine $machine_id"$'\n' -n 1 good_to_go
+  read -r -s -p "press 'y' to permanently delete this machine $machine_id"$'\n' -n 1 good_to_go
   if [[ "$good_to_go" == 'y' ]]; then
     return 0
   fi
   return 1
 }
 
+get_instance_id() {
+  local machine_id="$1"
+  aws ec2 describe-instances --filters "Name=tag:Name,Values=$machine_id" | jq --raw-output '.Reservations[].Instances[0].InstanceId'
+}
+
+terminate_machine() {
+  local machine_id="$1"
+  local instance_id
+  instance_id="$(get_instance_id "$machine_id")" || fatal 'Failed to get instance id in AWS'
+  aws ec2 terminate-instances --instance-ids "$instance_id"
+}
+
 main() {
   local machine_id
   while [ "$1" != "" ]; do
     local param="$1"
-    local value="$2"
+    # local value="$2"
     case "$param" in
       -h | --help)
         usage
@@ -99,6 +111,7 @@ main() {
   drain_machine "$machine_id"
   remove_docker_machine "$machine_id"
   remove_config "$machine_id"
+  terminate_machine "$machine_id"
 }
 
 main "$@"
