removed unnecessary scripts, unified the version and fixed some stuff in stack

diff --git a/stack/stack-create-machine b/stack/stack-create-machine
--- a/stack/stack-create-machine
+++ b/stack/stack-create-machine
@@ -43,6 +43,23 @@ select_random_zone(){
   echo "${zones[$rand]/,/}"
 }
 
+create_machine() {
+  local machine_id="$1"; shift;
+  local options="$@"
+  echo "$(docker-machine create $options "$machine_id")"
+}
+
+copy_to_template() {
+  local machine_id="$1"
+  local src_dir="$2"
+  local dest_dir="$3"
+
+  cp -rfp "$src_dir/$machine_id" "$dest_dir/$machine_id"
+  local config_file="$dest_dir/$machine_id/config.json"
+  cat "$config_file" | sed "s;$HOME;\$HOME;g" > "$config_file.tmp" && \
+    mv "$config_file.tmp" "$config_file"
+}
+
 usage(){
   echo 'USAGE: stack-create-machine'
   echo ''
@@ -56,7 +73,7 @@ usage(){
 }
 
 version(){
-  local directory="$(script_directory)"
+  local directory="$(script_directory)/.."
 
   if [ -f "$directory/VERSION" ]; then
     cat "$directory/VERSION"
@@ -107,7 +124,13 @@ main() {
   debug "using ec2 zone $ec2_zone"
   debug "using ec2 instance type $ec2_instance_type"
 
-  swarm-create-machine "$machine_id" -- \
+  local template_dir=""
+
+  assert_required_params "$machine_id"
+
+  echo "Creating $machine_id"
+  
+  create_machine "$machine_id" \
     --driver amazonec2 \
     --amazonec2-access-key "$AWS_ACCESS_KEY_ID" \
     --amazonec2-secret-key "$AWS_SECRET_ACCESS_KEY" \
@@ -116,8 +139,16 @@ main() {
     --amazonec2-root-size "100" \
     --amazonec2-instance-type "$ec2_instance_type" \
     --amazonec2-security-group "swarm-prod" \
-    --amazonec2-security-group "swarm-prod-ssh"
+    --amazonec2-security-group "swarm-prod-ssh" || fatal 'unable to create machine'
 
+  mkdir -p $STACK_ENV_DIR/machine/machines
+  mkdir -p $STACK_ENV_DIR/machine-template/machines
+  mkdir -p $STACK_ENV_DIR/machine-template/certs
+  copy_to_template "$machine_id" \
+    $STACK_ENV_DIR/machine/machines \
+    $STACK_ENV_DIR/machine-template/machines || fatal 'unable to copy machine templates'
+
+  cp -rfp $STACK_ENV_DIR/machine/certs/* $STACK_ENV_DIR/machine-template/certs/
 }
 
 main "$@"
diff --git a/stack/stack-initialize b/stack/stack-initialize
--- a/stack/stack-initialize
+++ b/stack/stack-initialize
@@ -36,7 +36,7 @@ usage(){
 }
 
 version(){
-  local directory="$(script_directory)"
+  local directory="$(script_directory)/.."
 
   if [ -f "$directory/VERSION" ]; then
     cat "$directory/VERSION"
@@ -138,6 +138,26 @@ unset_stack_env() {
   eval $(docker-machine env --unset)
 }
 
+get_interface() {
+  local machine_id="$1"
+  local ifconf="$(docker-machine ssh "$machine_id" ifconfig)"
+  if [ "$?" != "0" ]; then
+    fatal 'Unable to ssh into machine'
+    return 1
+  fi
+  echo "$ifconf" | grep eth0 &> /dev/null
+  if [ "$?" == "0" ]; then
+    echo 'eth0'
+    return 0
+  fi
+  echo "$ifconf" | grep ens3 &> /dev/null
+  if [ "$?" == "0" ]; then
+    echo 'ens3'
+    return 0
+  fi
+  return 1
+}
+
 main() {
   local ec2_instance_type="t2.medium"
   local stack_env_name
@@ -201,7 +221,16 @@ main() {
   debug 'sleep for 10 seconds to wait for docker'
   sleep 10
   eval $(docker-machine env --shell=bash "$machine_id")
-  swarm-initialize "$machine_id" || fatal 'unable to initialize swarm'
+
+  local interface="$(get_interface "$machine_id")"
+  if [ "$?" != "0" ]; then
+    fatal "$interface"
+  fi
+
+  docker $(docker-machine config "$machine_id") \
+    swarm init \
+    --advertise-addr "$interface" \
+    --listen-addr "$interface" || fatal 'unable to initialize swarm'
 
   if [ "$skip_elb" != "true" ]; then
     local lb_name="${stack_env_name}-${stack_name}"
